### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by gcottrell1** [connectedcars/react-native-slide-charts#18]
Great library!

Please can you create a new release to include 342560c49a48e8458dd7aed94ec896c7d3754d28 as the casing issue is causing TSC builds to fail on CI

Thanks

**Comment by brunolipe-a** [comment]
Same problem here!

Please, make a release...

**Comment by gcottrell1** [comment]
@nhannah any chance of `v1.0.5`?

**Comment by Kjagd** [comment]
@gcottrell1 @brunolipe-a
Hey! We've moved the package to our organization, so we are able to publish again.
1.0.5 is available here now: https://www.npmjs.com/package/@connectedcars/react-native-slide-charts
