### ISSUE TITLE
Tool Tip Default Position

### ISSUE THREAD

**Issue by Billwall2020** [connectedcars/react-native-slide-charts#20]
Is there a possibility to set the default position of the tool tip/y value to the last value in the data array and not to the middle?

Thanks in advance!

**Comment by simona-iuliana** [comment]
const chartRef = React.useRef(null);
useEffect(() => {
        chartRef.current.state.x.setValue(
            ((widthChart - chartRef.current.props.paddingLeft - chartRef.current.props.paddingRight) / 11) *
                (getCurrentMonth() - 1),
        );
    }, [chartRef]);
