### ISSUE TITLE
curveType prop not changing line shape

### ISSUE THREAD

**Issue by scaralfred** [connectedcars/react-native-slide-charts#22]
I have tried to change the line shape from "curve" to "simple line" by adding this code:

import * as shape from 'd3-shape';

 <SlideAreaChart
    curveType={shape.CurveFactoryLineOnly}
    ...all the other props
/>

But the line stays a curve, not changing to a normal line.
Specifically I'm trying to achieve the "curveLinearClosed" from https://github.com/d3/d3-shape#curves

I might have misinterpreted the documentation. Hope someone can help.

**Comment by scaralfred** [comment]
solved. I just used this property => shape.curveLinear

**Comment by navid-asgharzadeh** [comment]
@scaralfred Where did you add it?
