### ISSUE TITLE
npm install @connectedcars/react-native-slide-charts --save is not Working 

### ISSUE THREAD

**Issue by imransiddiquiandroid** [connectedcars/react-native-slide-charts#26]
![Screenshot (239)](https://user-images.githubusercontent.com/78909064/115394716-b082e480-a200-11eb-8e25-f6966259bdd1.png)

**Comment by asp3** [comment]
having the same issue^

**Comment by ANIBIT14** [comment]
Same issue any resolution for this

**Comment by RaySkelen** [comment]
In my case this was the solution: 

1. Delete the node_modules folder.
2. Run `yarn install`
3. Run 'yarn add react-native-slide-charts'

I have tried to delete modules and `npm i` afterwards, but got the same error as in the picture above.
