### ISSUE TITLE
Drag & drop datapoints

### ISSUE THREAD

**Issue by jcarioti** [connectedcars/react-native-slide-charts#27]
Does this lib support dragging/movement of the datapoints at all? I've yet to find a react native charting library that allows for interactive data.

**Comment by Kjagd** [comment]
Sorry, this is not implemented currently.

**Comment by sadia-onyxtec** [comment]
@jcarioti, Did you happen to find any library that allows dragging/movement of the datapoints?

**Comment by jcarioti** [comment]
@sadia-onyxtec No, I haven’t found one. Sorry.
