### ISSUE TITLE
Does not render with React Native Web using Expo. 

### ISSUE THREAD

**Issue by Lurtroxx** [connectedcars/react-native-slide-charts#37]
I cannot get the component to render using the web. It also does not render on the snack for the example.

**Comment by Lurtroxx** [comment]
Wrong repo. Sorry.

**Comment by Kjagd** [comment]
Hi, unfortunately something is broken with Expo. It doesn't seem that trivial to fix unfortunatly. Closing since it's a duplicate of https://github.com/connectedcars/react-native-slide-charts/issues/11
