### ISSUE TITLE
How to prevent Interpolation between values by cursor?

### ISSUE THREAD

**Issue by maitham** [connectedcars/react-native-slide-charts#6]
How do you prevent interpolation between the values on the graph when scrolling using the cursor?

**Comment by nhannah** [comment]
Do you want just the values to jump or do you want the actual cursor to only move to the x locations that have values associated?

**Comment by maitham** [comment]
just the values to jump

**Comment by nhannah** [comment]
You should be able to use the inputs to the toolTip to back track to some source data. i.e. inverse the xScale of x to get the current X value in your source array and use custom logic to determine which associated Y to display, could just be rounding if it's all sequential X values in your array.

**Comment by amansoorhq** [comment]
> 
> 
> Do you want just the values to jump or do you want the actual cursor to only move to the x locations that have values associated?

Can you give any idea on how to move the actual cursor to the x locations that have value associated?
